---
# file: roles/firewall/tasks/fail2ban.yml
- name: install fail2ban
  apt:
    name: fail2ban
    state: latest
- name: copy jail.local
  copy:
    remote_src: yes
    src: /etc/fail2ban/jail.conf
    dest: /etc/fail2ban/jail.local
    owner: root
    group: root
    mode: 0440
- name: make sure fail2ban is running and enabled on startup
  service:
    name: fail2ban
    state: started
    enabled: yes
