---
# file: roles/common/tasks/users.yml
- name: set hostname
  hostname:
    name: "{{ inventory_hostname_short }}"
- name: set hostname in /etc/hosts
  replace:
    path: /etc/hosts
    regexp: "127.0.1.1\t.+"
    replace: "127.0.1.1\t{{ inventory_hostname_short }}.{{ domain }} {{ inventory_hostname_short }}"
- name: execute hostname changes without rebooting
  shell: invoke-rc.d hostname.sh start
- name: create users
  user:
    name: "{{ item.name }}"
    shell: /bin/bash
    state: present
  with_items: "{{ users }}"
- name: create sudoers
  copy:
    content: "{{ item.name }} ALL=(ALL) NOPASSWD:ALL"
    dest: "/etc/sudoers.d/90-{{ item.name }}"
    owner: root
    group: root
    mode: 0440
  with_items: "{{ users }}"
- name: add ssh keys to authorized keys
  authorized_key:
    user: "{{ item.name }}"
    state: present
    key: "{{ lookup('file', item.key) }}"
  with_items: "{{ users }}"
- name: disable password authentication through ssh
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^PasswordAuthentication'
    line: 'PasswordAuthentication no'
    state: present
  notify: reload ssh
- name: disable root login through ssh
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^PermitRootLogin'
    line: 'PermitRootLogin no'
    state: present
  notify: reload ssh
